#!/usr/bin/env python3
"""Dependency-free static site generator. Edit content/, then run this file."""
from pathlib import Path
import html, json, re, shutil, os
from datetime import date
from urllib.parse import quote
from xml.etree.ElementTree import Element, SubElement, ElementTree

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
S=json.loads((ROOT/'content/site.json').read_text())
SERVICES=json.loads((ROOT/'content/services.json').read_text())
ONLINE=json.loads((ROOT/'content/online-consultation.json').read_text())
POSTS=sorted([json.loads(p.read_text()) for p in (ROOT/'content/posts').glob('*.json')],key=lambda p:(p['date'],p.get('featured',False),p['slug']),reverse=True)
BASE=S['url'].rstrip('/')
PREFIX=os.environ.get('SITE_PATH_PREFIX','').rstrip('/')
DATE=S['updated']
LOGO='tugba-monogram.svg'
MONTHS=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık']
def display_date(value):
    d=date.fromisoformat(value)
    return f'{d.day} {MONTHS[d.month-1]} {d.year}'
e=lambda s:html.escape(str(s),quote=True)
def path(s):return PREFIX+s if s.startswith('/') else s
def link(url,label,cls='',external=False):
    extra=' target="_blank" rel="noopener noreferrer"' if external else ''
    return f'<a href="{e(path(url))}" class="{cls}"{extra}>{label}</a>'
def btn(url,label,light=False):return link(url,e(label)+' <span aria-hidden="true">↗</span>','button'+(' light' if light else ''),url.startswith('https:'))
WA='https://wa.me/'+S['phone'].replace('+','')+'?text='+quote('Merhaba, online beslenme danışmanlığı ve görüşme süreci hakkında bilgi almak istiyorum.')
def img(file,alt,cls='',eager=False):
    dims={'tugba-seker-agac.webp':(1200,1048),'adana-ofis.webp':(760,722),'tugba-klinik.webp':(952,868),'dengeli-beslenme.webp':(1400,933),'surdurulebilir-beslenme.webp':(1200,1600),'online-diyetisyen-kapak.webp':(1077,519),'tugba-kurumsal.webp':(1200,1600),'tugba-hizmetler.webp':(1200,1600),'tugba-blog-calisma.webp':(1200,800),'tugba-logo.webp':(221,292),'iskelet.webp':(1180,1200),'kas.webp':(803,628),'yag-dokusu.webp':(1200,482),'sindirim.webp':(450,531)}
    dims[LOGO]=(640,640)
    w,h=dims.get(file,(480,360) if file.startswith('video-') else (1280,720));load='fetchpriority="high"' if eager else 'loading="lazy"'
    return f'<img src="{e(path("/assets/images/"+file))}" alt="{e(alt)}" width="{w}" height="{h}" class="{cls}" {load} decoding="async">'
def brand(eager=False):
    logo=img(LOGO,'Tuğba Şeker Ağaç TŞA monogramı','brand-logo',eager=eager)
    return logo+'<div class="brand-copy"><small>DİYETİSYEN</small><strong>Tuğba Şeker Ağaç</strong><span>BESLENME &amp; DANIŞMANLIK</span></div>'
NAV=[('Ana Sayfa','/'),('Kurumsal','/kurumsal/'),('Online Diyetisyen','/online-diyetisyen/'),('Hizmetler','/hizmetler/'),('Blog','/blog/'),('İletişim','/iletisim/')]
PAGES=[]
def layout(route,title,desc,body,kind='WebPage',extra=None,noindex=False,cover='tugba-seker-agac.webp'):
    canonical=BASE+route
    article=next((x for x in (extra or []) if x.get('@type')=='BlogPosting'),None)
    modified=article['dateModified'] if article else S.get('page_updates',{}).get(route,DATE)
    graph=[{'@type':'Person','@id':BASE+'/#diyetisyen','name':S['name'],'jobTitle':'Diyetisyen','url':BASE+'/kurumsal/','image':BASE+'/assets/images/tugba-seker-agac.webp','alumniOf':{'@type':'CollegeOrUniversity','name':'Erciyes Üniversitesi'},'sameAs':[S[x] for x in ['instagram','youtube','linkedin','reddit']]},
      {'@type':'ProfessionalService','@id':BASE+'/#kurum','name':S['name'],'url':BASE+'/','telephone':S['phone'],'image':BASE+'/assets/images/adana-ofis.webp','logo':BASE+'/assets/images/'+LOGO,'founder':{'@id':BASE+'/#diyetisyen'},'areaServed':{'@type':'Country','name':'Türkiye'},'address':{'@type':'PostalAddress','streetAddress':S['address'].split(', Seyhan')[0],'addressLocality':'Seyhan','addressRegion':'Adana','postalCode':'01010','addressCountry':'TR'},'geo':{'@type':'GeoCoordinates','latitude':S['latitude'],'longitude':S['longitude']},'hasMap':S['map']},
      {'@type':'WebSite','@id':BASE+'/#website','url':BASE+'/','name':S['name'],'inLanguage':'tr-TR','publisher':{'@id':BASE+'/#kurum'}},
      {'@type':kind,'@id':canonical+'#webpage','url':canonical,'name':title,'description':desc,'inLanguage':'tr-TR','dateModified':modified,'isPartOf':{'@id':BASE+'/#website'},'about':{'@id':BASE+'/#diyetisyen'}}]
    if route!='/':graph.append({'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Ana Sayfa','item':BASE+'/'},{'@type':'ListItem','position':2,'name':title.split('|')[0].strip(),'item':canonical}]})
    if extra:graph.extend(extra)
    nav=''.join(f'<a href="{e(path(u))}"'+(' aria-current="page"' if route==u or (u=='/blog/' and route.startswith('/blog/')) or (u=='/hizmetler/' and route.startswith('/hizmetler/')) else '')+f'>{t}</a>' for t,u in NAV)
    header=f'''<a href="#main" class="skip">İçeriğe geç</a><div class="topbar"><div class="wrap"><span>TÜRKİYE GENELİNDE ONLINE · ADANA’DA YÜZ YÜZE DANIŞMANLIK</span><span>WhatsApp: Pazartesi–Cumartesi 08.00–20.00</span></div></div><header class="site-header"><div class="wrap nav-wrap">{link('/',brand(eager=True),'brand')}<button class="menu-toggle" type="button" aria-label="Gezinme menüsü" aria-expanded="false" aria-controls="site-nav">Menü ☰</button><nav id="site-nav" class="nav" aria-label="Ana gezinme">{nav}{btn(WA,'Görüşme bilgisi')}</nav></div></header>'''
    footlinks=''.join(link(u,e(t)) for t,u in NAV[1:])
    social=''.join(link(S[k],v,external=True) for k,v in [('instagram','Instagram'),('youtube','YouTube'),('linkedin','LinkedIn'),('reddit','Reddit')])
    footer=f'''<section class="cta-band"><div class="wrap"><div><span class="eyebrow">BESLENME DANIŞMANLIĞI</span><h2>Size uygun bir başlangıcı konuşalım.</h2><p>Online görüşme veya Adana ofisi için iletişim ve randevu bilgileri.</p></div>{btn('/iletisim/','İletişime geçin')}</div></section><footer class="site-footer"><div class="wrap"><div class="footer-grid"><div>{link('/',brand(),'brand')}<p>Türkiye genelinde online diyetisyen danışmanlığı ve Adana’da yüz yüze beslenme görüşmeleri.</p><p>İçerikler genel bilgilendirme amaçlıdır. Kişisel tanı, tedavi veya beslenme planı yerine geçmez.</p></div><div><h3>KEŞFEDİN</h3><div class="footer-links">{footlinks}</div></div><div><h3>BİLGİ &amp; KAYNAKLAR</h3><div class="footer-links">{link('/vucudunu-tani/','Vücudunu Tanı')}{link('/bki-hesaplama/','BKİ Hesaplama')}{link('/videolar/','Videolar')}{link('/kaynaklar/','Kaynaklar ve içerik ilkeleri')}{link('/gizlilik/','Gizlilik ve veri kullanımı')}</div></div><div><h3>ADANA OFİSİ &amp; ONLINE</h3><p>{e(S['address'])}</p><div class="footer-links">{link('tel:'+S['phone'],e(S['phone_display']))}{link(S['map'],'Konumu aç ↗',external=True)}{link(WA,'WhatsApp ↗',external=True)}</div><p style="margin-top:18px">WhatsApp: {e(S['whatsapp_hours'])}<br>Pazar kapalı · Ofis görüşmeleri randevuyla.</p><div class="social-list">{social}</div></div></div><div class="footer-bottom"><p>© 2026 {e(S['name'])}.<br>İçerik güncelleme: {display_date(modified)} · Editör iletişimi: {link('tel:'+S['phone'],e(S['phone_display']))}</p><p>{link('/adana-diyetisyen/','Adana diyetisyen')} · {link('/online-diyetisyen/','Online diyetisyen')} · {link('/feed.xml','RSS')}</p></div></div></footer>{link(WA,'WhatsApp · Görüşme bilgisi ↗','floating-contact',True)}<div class="mobile-contact" aria-label="Hızlı iletişim">{link('tel:'+S['phone'],'Telefonla ara')}{link(S['instagram'],'Instagram',external=True)}{link(WA,'WhatsApp ↗',external=True)}</div>'''
    doc=f'''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="robots" content="{'noindex,follow' if noindex else 'index,follow,max-image-preview:large'}"><link rel="canonical" href="{e(canonical)}"><meta name="theme-color" content="#164e33"><link rel="icon" type="image/svg+xml" sizes="any" href="{path('/assets/images/'+LOGO)}"><link rel="alternate" type="application/rss+xml" title="Beslenme Blogu" href="{path('/feed.xml')}"><meta property="og:type" content="{'article' if article else 'website'}"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="{e(S['name'])}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{e(canonical)}"><meta property="og:image" content="{BASE}/assets/images/{cover}"><meta property="og:image:alt" content="{e(S['name'])} beslenme rehberi"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="{path('/assets/style.css')}?v=green-refresh"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('<','\\u003c')}</script><script defer src="{path('/assets/calculator.js')}"></script><script defer src="{path('/assets/app.js')}"></script><noscript><style>.nav{{display:flex;position:static;flex-wrap:wrap;flex-direction:row}}.menu-toggle{{display:none}}.nav-wrap{{flex-wrap:wrap}}</style></noscript></head><body>{header}<main id="main">{body}</main>{footer}</body></html>'''
    if PREFIX:
        # Content HTML also uses absolute internal URLs.
        doc=re.sub(r'(href|src)="/(?!/|'+re.escape(PREFIX.lstrip('/'))+r'(?:/|"))',lambda m:m[1]+'="'+PREFIX+'/',doc)
    filename=OUT/('index.html' if route=='/' else '404.html' if route=='/404.html' else route.strip('/')+'/index.html')
    filename.parent.mkdir(parents=True,exist_ok=True);filename.write_text(doc)
    if not noindex:PAGES.append((route,title,modified))

def eyebrow(s):return f'<span class="eyebrow">{e(s)}</span>'
def heading(kicker,title,desc='',more=None):return '<div class="section-heading"><div>'+eyebrow(kicker)+f'<h2>{title}</h2>'+('<p class="muted">'+desc+'</p>' if desc else '')+'</div>'+(link(more[0],more[1]+' <span aria-hidden="true">↗</span>','text-link') if more else '')+'</div>'
def hero(title,intro,kicker,photo=None,photo_cls='',photo_alt=None):
    crumb=f'<div class="breadcrumb">{link("/","Ana Sayfa")} / {e(kicker)}</div>'
    copy=eyebrow(kicker)+f'<h1>{title}</h1><p class="lead">{intro}</p>'
    return '<section class="page-hero'+(' has-photo' if photo else '')+'"><div class="wrap">'+crumb+('<div class="split"><div>'+copy+'</div>'+img(photo,photo_alt or S['name'],photo_cls,eager=True)+'</div>' if photo else copy)+'</div></section>'
def cards(items=SERVICES):
    return '<div class="grid-3">'+''.join(f'<article class="service-card"><span class="number" aria-hidden="true">{i:02}</span><h3>{link("/hizmetler/"+s["slug"]+"/",e(s["title"]))}</h3><p>{e(s["short"])}</p>{link("/hizmetler/"+s["slug"]+"/","İçeriği inceleyin <span aria-hidden=\"true\">↗</span>","text-link")}</article>' for i,s in enumerate(items,1))+'</div>'
def steps():
    values=[('Tanışalım','Günlük düzeninizi, beklentilerinizi ve mevcut sağlık bilgilerinizi konuşalım.'),('Birlikte planlayalım','Öğünlerinizi yaşam ritminize, tercihlerinize ve gereksinimlerinize göre ele alalım.'),('Takip edelim','Uygulama deneyiminizi haftalık görüşmelerde değerlendirelim.'),('Hayatınıza uyarlayalım','İhtiyaçlarınıza göre alternatifler ve sürdürülebilir alışkanlıklar üzerinde çalışalım.')]
    return '<div class="steps">'+''.join(f'<div class="step"><span aria-hidden="true">{i:02}</span><h3>{a}</h3><p>{b}</p></div>' for i,(a,b) in enumerate(values,1))+'</div>'
FAQ=[('Online diyetisyen görüşmesi hangi şehirlerde yapılabilir?','Türkiye’nin farklı şehirlerinden online görüşmeye katılabilirsiniz. İhtiyaçlarınız ve online görüşmeye uygunluk ilk iletişimde değerlendirilir. Adana’da yüz yüze görüşme seçeneği de vardır.'),('İlk görüşmede ne konuşulur?','Sağlık öykünüz, mevcut tanılarınız, günlük öğünleriniz, çalışma düzeniniz, hareket alışkanlıklarınız ve beklentileriniz değerlendirilir. Mevcut tetkiklerinizi ve ilaç bilgilerinizi hazır bulundurabilirsiniz.'),('Beslenme listesi herkese aynı mı hazırlanır?','Plan; sağlık durumunuz, gereksinimleriniz ve günlük yaşamınız dikkate alınarak kişiye göre düzenlenir. Öğün alternatifleri takipte yeniden değerlendirilebilir.'),('WhatsApp üzerinden hangi saatlerde iletişim kurabilirim?','Pazartesi–cumartesi günleri 08.00–20.00 arasında iletişim kurabilirsiniz. Pazar günleri kapalıdır. Görüşmeler önceden belirlenen randevu saatinde yapılır.'),('BKİ aracı yağ oranımı gösterir mi?','Hayır. Araç boy ve ağırlık üzerinden beden kütle indeksini hesaplar. Yağ veya kas oranınızı ölçmez; tanı koymaz. 20 yaş altı ve gebelik için kullanılmaz.'),('Ne kadar sürede sonuç alırım?','Süreç kişinin sağlık durumuna, gereksinimlerine ve günlük koşullarına göre değişir. Belirli sürede kesin kilo değişimi veya aynı sonucu elde etme garantisi verilmez.')]
def faqs(items=FAQ):return '<div class="faq">'+''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in items)+'</div>'
def bmi():return '''<div class="calc"><h3>Beden kütle indeksini hesapla</h3><p>Boy ve kilo bilgilerinle genel bir tarama göstergesi olan BKİ’ni öğren.</p><form data-bmi-form novalidate><fieldset disabled style="border:0;padding:0;margin:0"><div class="input-grid"><label>Boy (cm)<input name="height" inputmode="decimal" autocomplete="off" placeholder="Örn. 165" aria-label="Boy, santimetre" required></label><label>Kilo (kg)<input name="weight" inputmode="decimal" autocomplete="off" placeholder="Örn. 65" aria-label="Kilo, kilogram" required></label><label>Yaş<input name="age" inputmode="numeric" autocomplete="off" placeholder="20 ve üzeri" required></label></div><label class="checkbox"><input type="checkbox" name="eligible">20 yaş veya üzerindeyim ve gebelik durumum yok. Bu aracın tanı veya yağ ölçümü olmadığını biliyorum.</label><button class="button" type="submit">BKİ’mi hesapla <span aria-hidden="true">↗</span></button></fieldset><p class="calc-error" data-error role="alert"></p><div class="calc-result" data-result aria-live="polite" hidden><strong></strong><p data-category></p><p>Bu sonuç tek başına sağlık durumunuzu göstermez. Kas kütlesi ve sağlık öykünüz gibi etkenlerle birlikte yorumlanmalıdır.</p></div></form><p class="calc-note">Bilgileriniz kaydedilmez veya sunucuya gönderilmez. Hesaplama yalnızca bu cihazda yapılır. <a href="https://www.cdc.gov/bmi/adult-calculator/index.html" target="_blank" rel="noopener noreferrer"><u>Kaynak: CDC</u></a></p><noscript><p>Hesaplayıcı için JavaScript gerekir. Formül: ağırlık (kg) ÷ boy (m)². Yetişkin sınıflaması yalnızca uygun kişilerde yorumlanır.</p></noscript></div>'''

ANATOMY=[
 ('iskelet','Kemikler','Vücudunun destek sistemi','Kemikler vücuda destek sağlar, organları korur ve kaslarla birlikte hareketi mümkün kılar. Kalsiyum ile D vitamini kemik sağlığının beslenmeyle ilgili parçalarıdır.','Beslenme bağlantısı: besin çeşitliliği ve bireysel gereksinimler.','iskelet.webp','İskeletin önden ve arkadan görünümü; merkezi iskelet ve uzuv kemikleri','https://commons.wikimedia.org/wiki/File:701_Axial_Skeleton-01.jpg','3.0','https://ods.od.nih.gov/factsheets/Calcium-Consumer/'),
 ('kas','Kaslar','Hareketin arkasındaki doku','İskelet kasları lif demetlerinden oluşur. Kasılma sırasında enerji kullanılır ve kuvvet tendonlar aracılığıyla kemiklere aktarılır.','Beslenme bağlantısı: öğünlerin bütünü, enerji gereksinimi ve aktivite düzeyi.','kas.webp','Kas lifinin iç yapısını, miyofibrilleri ve sarkomeri gösteren çizim','https://commons.wikimedia.org/wiki/File:1002_Organization_of_Muscle_Fiber.jpg','4.0','https://openstax.org/books/anatomy-and-physiology-2e/pages/10-2-skeletal-muscle'),
 ('yag','Yağ dokusu','Bir sayıdan fazlası','Yağ dokusu enerji depolayan ve vücudun yalıtımında rol alan bir dokudur. Tartıdaki toplam ağırlık, bu dokunun miktarını tek başına göstermez.','Beslenme bağlantısı: yağ dokusunu anlamak, kilo takibini daha doğru yorumlamak.','yag-dokusu.webp','Yağ hücreleri, çekirdekleri ve yağ damlacıklarını gösteren çizim ve mikroskop görüntüsü','https://commons.wikimedia.org/wiki/File:409_Adipose_Tissue.jpg','3.0','https://openstax.org/books/anatomy-and-physiology-2e/pages/4-3-connective-tissue-supports-and-protects'),
 ('sindirim','Sindirim','Yediğin besinin yolculuğu','Sindirim ağızda başlar. Mide ve bağırsaklar besinlerin parçalanması ve emiliminde görev alır. Besin öğelerinin büyük bölümü ince bağırsaktan emilir.','Beslenme bağlantısı: öğün düzeni, bireysel tolerans ve sindirim yakınmalarının değerlendirilmesi.','sindirim.webp','Ağız, yemek borusu, mide, karaciğer, pankreas ve bağırsakların anatomik yerleşimi','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works',None,'https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works')]
def attribution(file):
    if file=='surdurulebilir-beslenme.webp':return 'Görsel: Diyetisyen Tuğba Şeker Ağaç tarafından sağlanan özgün Canva tasarımı.'
    if file=='online-diyetisyen-kapak.webp':return 'Görsel: Diyetisyen Tuğba Şeker Ağaç tarafından sağlanan özgün Canva tasarımı.'
    a=next((x for x in ANATOMY if x[5]==file),None)
    if not a:return 'Yapay zekâyla hazırlanmış temsili öğün görseli; kişisel diyet reçetesi değildir.' if file=='dengeli-beslenme.webp' else ''
    license=f' · <a href="https://creativecommons.org/licenses/by/{a[8]}/" target="_blank" rel="noopener noreferrer">CC BY {a[8]}</a>' if a[8] else ''
    return f'<a href="{a[7]}" target="_blank" rel="noopener noreferrer">{"OpenStax" if a[8] else "NIDDK / NIH"}</a>{license} · WebP dönüşümü ve boyutlandırma. Özgün etiketler İngilizcedir.'
def anatomy():
    buttons=''.join(f'<button class="chip" type="button" data-topic="{a[0]}" aria-pressed="false" aria-controls="anat-{a[0]}">{a[1]}</button>' for a in ANATOMY)
    panels=''.join(f'<div class="anatomy-panel" data-panel="{a[0]}" id="anat-{a[0]}"><h3>{a[2]}</h3><p>{a[3]}</p><p class="micro">{a[4]}</p><p class="micro">{link(a[9],"Bilimsel kaynağı inceleyin ↗",external=True)}</p></div>' for a in ANATOMY)
    figs=''.join(f'<figure class="anatomy-art" data-figure="{a[0]}">{img(a[5],a[6])}<figcaption>{attribution(a[5])}</figcaption></figure>' for a in ANATOMY)
    return f'<div class="anatomy" data-anatomy><div>{eyebrow("BESLENMENİN BİLİMİ")}<h2>Vücudunu tanı.<br><span class="accent">İhtiyacını anla.</span></h2><div class="anatomy-controls" role="group" aria-label="Anatomi konusu" data-js-only hidden>{buttons}</div>{panels}{link("/vucudunu-tani/","Anatomi rehberini keşfedin ↗","text-link")}</div><div>{figs}</div></div>'
def post_cards(posts=POSTS,searchable=False):
    out=[]
    for p in posts:
        u='/blog/'+p['slug']+'/'
        attrs=f' data-post data-category="{e(p["category"])}" data-search="{e(p["title"]+" "+p["description"])}"' if searchable else ''
        cover_class='post-cover'+(' science' if p.get('science') else '')+(' portrait' if p.get('portrait') else '')
        cover=link(u,img(p['image'],p['image_alt']),cover_class)
        out.append(f'<article class="post-card"{attrs}>{cover}<div class="micro">{e(p["category"])} · {reading_time(p)} dk okuma</div><h3>{link(u,e(p["title"]))}</h3><p>{e(p["description"])}</p>{link(u,"Yazıyı okuyun ↗","text-link")}</article>')
    return '<div class="grid-3">'+''.join(out)+'</div>'
def reading_time(p):return max(2,round(len(re.sub('<[^>]+>',' ',p['intro']+' '.join(s['body'] for s in p['sections'])).split())/180))
VIDEOS=[('yJBjeg2Csrs','Ramazan ayında beslenme','Ramazan dönemindeki beslenme düzenine ilişkin kanal paylaşımı.'),('6IfEDX0r8zQ','Şekersiz kek tarifi','Evde hazırlanabilecek tariflere kanaldan bir örnek.'),('U-Ae6qZYAZs','Çorba tarifi','Günlük mutfağa uygun bir tarif videosu.')]
def video_cards():
    return '<div class="grid-3">'+''.join(f'<article class="video-card"><div class="video-slot"><button class="video-load" type="button" data-video="{v}" data-title="{e(t)}" aria-label="{e(t)} videosunu oynat">{img("video-"+v+".webp",t+" video kapağı")}<span class="play" aria-hidden="true">▶</span></button></div><h3>{e(t)}</h3><p>{e(d)}</p>{link("https://www.youtube.com/watch?v="+v,"YouTube’da aç ↗","text-link",True)}</article>' for v,t,d in VIDEOS)+'</div>'
def social_block():return f'''<div class="social-feature"><div>{eyebrow('INSTAGRAM’DA BULUŞALIM')}<h2>Beslenmeyi günlük hayatın içinde konuşuyoruz.</h2><p>Tarifler, beslenme notları ve gündelik sorulara ilişkin paylaşımlar için resmî Instagram hesabı.</p>{link(S['instagram'],'@dyt.tugbasekeragac ↗','text-link',True)}<div class="social-list">{link(S['youtube'],'YouTube ↗',external=True)}{link(S['linkedin'],'LinkedIn ↗',external=True)}{link(S['reddit'],'Reddit ↗',external=True)}</div></div>{img('adana-ofis.webp','Tuğba Şeker Ağaç, danışmanlık ofisinde')}</div>'''
REVIEWS=[
    ('Sibel B.','“Sıkmadan, yormadan destek olan bir yol arkadaşı.”'),
    ('Neslihan K.','“Hayatı düzene sokan, sürdürülebilir bir beslenme tarzı.”'),
    ('A. A.','“Keyifli ve öğretici bir süreç; sağlıklı yaşam alışkanlığı kazandırıyor.”'),
]
def reviews_block():
    rating=str(S.get('review_rating',5.0)).replace('.',',')
    count=e(S.get('review_count',''))
    reviews_url=S.get('reviews_url',S['map'])
    cards=''.join(f'<article class="review-card"><div class="review-stars" aria-label="5 yıldız">★★★★★</div><blockquote>{e(quote)}</blockquote><div class="review-meta"><strong>{e(name)}</strong><br><span>Google İşletme Profili · kısa alıntı</span></div></article>' for name,quote in REVIEWS)
    return f'''<section class="section review-section"><div class="wrap"><div class="section-heading"><div>{eyebrow('DANIŞAN DENEYİMLERİ')}<h2>İyi hissettiren bir süreç.</h2><p class="muted">Google İşletme Profilindeki gerçek değerlendirmelerden kısa bir seçki.</p></div>{btn(reviews_url,'Google’da tüm yorumları gör',True)}</div><div class="review-summary"><span class="review-score">{rating}</span><span class="review-stars" aria-hidden="true">★★★★★</span><span class="review-count">Google’da {count} yorum</span></div><div class="review-grid">{cards}</div><p class="review-note">Puan ve yorum sayısı Google profilinde zamanla değişebilir. Alıntılar okunaklı olması için kısaltılmıştır; tüm yorumlar Google profilinde yer alır.</p></div></section>'''
def sidebar():return f'<aside class="sidebar"><h3>Tanışalım.</h3><p>Online danışmanlık veya Adana ofisi için görüşme sürecini öğrenebilirsiniz.</p>{btn(WA,"WhatsApp ile iletişim")}{btn("tel:"+S["phone"],"Telefonla arayın",True)}<p>WhatsApp: {e(S["whatsapp_hours"])}<br>Pazar kapalı.</p><nav aria-label="İlgili sayfalar">{link("/online-diyetisyen/","Online danışmanlık süreci ↗")}{link("/vucudunu-tani/","Vücudunu Tanı ↗")}{link("/blog/","Diğer beslenme yazıları ↗")}</nav></aside>'
def article_body(content):return '<section class="section"><div class="wrap article-layout"><div class="prose">'+content+'</div>'+sidebar()+'</div></section>'

def build():
    if OUT.exists():shutil.rmtree(OUT)
    OUT.mkdir();shutil.copytree(ROOT/'assets',OUT/'assets')
    # The homepage is rendered at build time; important content never depends on JavaScript.
    body=f'''<section class="hero"><div class="wrap hero-grid"><div>{eyebrow('ONLINE DİYETİSYEN TUĞBA ŞEKER AĞAÇ')}<h1>Online diyetisyen ile<br><span class="accent">kendine iyi bak.</span></h1><p class="lead">Hayatına uyan öğünler, kişisel ihtiyaçların ve sürdürülebilir alışkanlıklar. Türkiye’nin neresinde olursan ol, beslenme düzenini birlikte ele alalım.</p><div class="actions">{btn('/online-diyetisyen/','Online danışmanlığı keşfet')}{btn('/kurumsal/','Beni tanıyın',True)}</div><div class="hero-meta"><div><b><span class="note-dot"></span>Türkiye genelinde</b>Online görüşme</div><div><b>Sana özel yaklaşım</b>Günlük yaşama uygun plan</div><div><b>Adana · Seyhan</b>Yüz yüze danışmanlık</div></div></div><figure class="hero-photo">{img('tugba-seker-agac.webp','Diyetisyen Tuğba Şeker Ağaç beyaz önlüğüyle',eager=True)}<figcaption class="photo-caption"><span>DİYETİSYEN</span><strong>Tuğba Şeker Ağaç</strong><span>Erciyes Üniversitesi · Beslenme ve Diyetetik</span></figcaption></figure></div></section>
    <div class="intro-band"><div class="wrap"><p>İyi beslenmek, hayatın içinde sürdürebildiğin bir dengeyle başlar.</p>{link('/vucudunu-tani/','Beslenmenin bilimini keşfet ↗','text-link')}</div></div>
    <section class="section"><div class="wrap">{heading('DANIŞMANLIK ALANLARI','Farklı ihtiyaçlar.<br><span class="accent">Kişisel bir yaklaşım.</span>','Kilo yönetiminden günlük beslenme alışkanlıklarına; ihtiyaçlarınızı birlikte değerlendirelim.',('/hizmetler/','Tüm hizmetler'))}{cards()}</div></section>
    <section class="section soft"><div class="wrap split">{img('adana-ofis.webp','Diyetisyen Tuğba Şeker Ağaç ofisinde','split-photo')}<div class="split-copy">{eyebrow('MERHABA, BEN TUĞBA')}<h2>Seni ve hayatını tanıyarak başlayalım.</h2><p>Erciyes Üniversitesi Beslenme ve Diyetetik mezunuyum. Adana’da yüz yüze, Türkiye genelinde online beslenme danışmanlığı sunuyorum.</p><p>Görüşmelerimizde günlük yaşamını, sağlık öykünü ve beklentilerini birlikte ele alıyoruz. Amacımız; sevdiğin yemeklere, işine ve sosyal hayatına yer açan bir düzen üzerinde çalışmak.</p><div class="fact-list"><div><strong>Eğitim</strong><span>Beslenme ve Diyetetik</span></div><div><strong>Görüşme</strong><span>Online &amp; Adana ofisi</span></div><div><strong>Yaklaşım</strong><span>Kişiye göre planlama ve takip</span></div></div>{link('/kurumsal/','Eğitimim ve çalışma yaklaşımım ↗','text-link')}</div></div></section>
    <section class="section dark"><div class="wrap">{heading('ONLINE DANIŞMANLIK SÜRECİ','Birlikte, adım adım.','Günlük hayatınızı anlayarak başlayan ve ihtiyaçlarınıza göre şekillenen bir süreç.')}{steps()}<div class="actions">{link('/online-diyetisyen/','Süreci ayrıntılı inceleyin ↗','button white')}</div></div></section>
    <section class="section"><div class="wrap">{anatomy()}</div></section>
    <section class="section soft"><div class="wrap split"><div>{eyebrow('KENDİNİ TANI')}<h2>Bir ölçüm.<br><span class="accent">Daha büyük bir resim.</span></h2><p class="lead" style="margin-top:22px">Boy ve kilo, vücudunla ilgili bilgilerin yalnızca bir parçası. BKİ sonucunu sınırlarını bilerek değerlendir.</p><p class="muted">Bu araç kas, yağ veya su oranını ölçmez. Sonuç kişisel sağlık bilgileriyle birlikte yorumlanmalıdır.</p>{link('/bki-hesaplama/','BKİ nasıl yorumlanır? ↗','text-link')}</div>{bmi()}</div></section>
    <section class="section"><div class="wrap">{heading('BESLENME NOTLARI','Merak ettiklerin için<br><span class="accent">bir bilgi köşesi.</span>','Günlük sorulara açık, kaynaklı ve anlaşılır beslenme yazıları.',('/blog/','Tüm yazıları keşfet'))}{post_cards([p for p in POSTS if p.get('featured')][:3])}</div></section>
    <section class="section soft"><div class="wrap">{heading('VİDEO KÖŞESİ','İzle, öğren, mutfağına taşı.','Tuğba Şeker Ağaç’ın YouTube kanalından seçilmiş videolar.',('/videolar/','Video arşivi'))}{video_cards()}<p class="micro" style="margin-top:22px">Oynat düğmesine basıldığında YouTube yüklenir.</p></div></section>
    <section class="section"><div class="wrap">{social_block()}</div></section>
    {reviews_block()}
    <section class="section"><div class="wrap">{heading('SIK SORULAN SORULAR','Başlamadan önce aklındakiler.')}{faqs()}</div></section>'''
    layout('/','Online Diyetisyen Tuğba Şeker Ağaç | Türkiye & Adana','Türkiye genelinde online diyetisyen Tuğba Şeker Ağaç ile kişisel beslenme danışmanlığı. Kilo yönetimi, kaynaklı beslenme rehberleri ve Adana ofisi.',body)

    online=hero('Türkiye genelinde<br><span class="accent">online diyetisyen danışmanlığı.</span>','Bulunduğunuz şehirden, kendi yaşam düzeniniz içinden beslenme görüşmelerine katılın. Süreci, kapsamını ve takip adımlarını bu sayfada öğrenin.','Online danışmanlık','online-diyetisyen-kapak.webp','wide-cover','Diyetisyen Tuğba Şeker Ağaç markasına ait online beslenme danışmanlığı kapak görseli')
    online+='<section class="section dark"><div class="wrap">'+heading('NASIL İLERLİYORUZ?','Hayatınızı tanıyan bir süreç.')+steps()+'</div></section>'
    content=''.join(f'<section id="{e(s["id"])}"><h2>{e(s["title"])}</h2>{s["body"]}</section>' for s in ONLINE['sections'])
    online+=article_body(content)+'<section class="section soft"><div class="wrap">'+heading('DANIŞMANLIK ALANLARI','Hangi konuda birlikte çalışabiliriz?')+cards()+'</div></section><section class="section"><div class="wrap">'+heading('SORULARINIZ','Online görüşme hakkında')+faqs()+'</div></section>'
    layout('/online-diyetisyen/','Online Diyetisyen | Türkiye Genelinde Tuğba Şeker Ağaç','Online diyetisyen danışmanlığı nasıl işler? İlk görüşme, kişisel beslenme planı, haftalık takip ve Türkiye genelinden katılım bilgileri.',online,cover='online-diyetisyen-kapak.webp')

    about=hero('Diyetisyen<br><span class="accent">Tuğba Şeker Ağaç.</span>','Bilimsel bilgiyi, günlük hayatın ihtiyaçlarıyla birlikte ele alan bir beslenme yaklaşımı.','Kurumsal · Hakkımda','tugba-kurumsal.webp',photo_alt='Diyetisyen Tuğba Şeker Ağaç, sahil kenarında gülümserken')
    about+=article_body('''<h2>Eğitim ve mesleki yaklaşım</h2><p>Tuğba Şeker Ağaç, Erciyes Üniversitesi Sağlık Bilimleri Fakültesi Beslenme ve Diyetetik Bölümü mezunudur. Lisans eğitimini 2019–2023 yılları arasında tamamlamıştır.</p><p>Adana’da yüz yüze ve Türkiye genelinde online beslenme danışmanlığı sunar. Danışmanlık görüşmelerinde sağlık öyküsü, yaşam tarzı, beslenme alışkanlıkları ve kişisel gereksinimler birlikte değerlendirilir.</p><h2>Günlük hayatınıza uyum</h2><p>Görüşmelerde yalnızca ne yediğiniz değil, öğünlerinizi nerede ve hangi koşullarda yediğiniz de konuşulur. İş saatleri, aile düzeni, bütçe, alışveriş alışkanlıkları ve sevilen yiyecekler planlama sırasında dikkate alınır.</p><p>Beslenme planının uygulanamayan noktaları takipte yeniden ele alınır. Herkesin aynı listeye uyum sağlaması beklenmez.</p><h2>Bilimsel ve anlaşılır bilgilendirme</h2><p>Sitedeki bilgi merkezinde kaslar, kemikler, yağ dokusu ve sindirim gibi temel konular kaynak bağlantılarıyla anlatılır. Genel bilgiler kişisel tanı veya tedavi iddiasıyla sunulmaz.</p><p>Gerektiğinde hekim veya diğer sağlık profesyonellerinin değerlendirmesiyle birlikte ilerlenir. Mesleki unvan olarak “Diyetisyen” kullanılır.</p><h2>Görüşmeler ve iletişim</h2><p>Online ve ofis görüşmeleri randevuyla planlanır. WhatsApp iletişim saatleri pazartesi–cumartesi 08.00–20.00’dır; pazar günleri kapalıdır.</p>''')
    about+='<section class="section soft"><div class="wrap">'+social_block()+'</div></section>'
    layout('/kurumsal/','Tuğba Şeker Ağaç Kimdir? | Diyetisyen & Kurumsal','Diyetisyen Tuğba Şeker Ağaç’ın eğitim bilgileri, çalışma yaklaşımı, online danışmanlık ve Adana’daki yüz yüze görüşmeler hakkında.',about,kind='AboutPage',cover='tugba-kurumsal.webp')

    services=hero('Beslenme danışmanlığı<br><span class="accent">ihtiyaçlarınıza göre.</span>','Kilo değişimi hedefinden günlük beslenme düzenine kadar farklı konular, kişisel değerlendirmeyle ele alınır.','Hizmetler','tugba-hizmetler.webp','portrait-cover','Diyetisyen Tuğba Şeker Ağaç beyaz önlüğüyle danışmanlık hizmetlerini anlatırken')+'<section class="section"><div class="wrap">'+cards()+'</div></section>'
    services+=article_body('<h2>Her plan değerlendirmeyle başlar</h2><p>Buradaki başlıklar görüşmelerde ele alınabilecek beslenme konularını açıklar. Hizmetin kapsamı ve online görüşmeye uygunluğu ilk iletişimde netleştirilir. Hastalıklarda beslenme, hekimin tanı ve tedavisiyle birlikte yürütülür.</p><h2>Yöntemler</h2><p>Türkiye genelinden online danışmanlık veya Adana Seyhan’daki ofiste yüz yüze görüşme seçenekleri bulunur. Görüşme sıklığı, takip yöntemi ve ihtiyaç duyulan bilgiler randevu sırasında konuşulur.</p>')
    layout('/hizmetler/','Beslenme Danışmanlığı Hizmetleri | Tuğba Şeker Ağaç','Kilo verme, kilo alma, hastalıklarda beslenme, aktif yaşam, gebelik ve emzirme döneminde online ve Adana’da beslenme danışmanlığı.',services,cover='tugba-hizmetler.webp')
    for s in SERVICES:
        content=''.join(f'<h2>{e(t)}</h2>{b}' for t,b in s['sections'])
        content+='<h2>İlgili beslenme yazısı</h2><p>'+link('/blog/'+s['related']+'/','Konuyu blogda ayrıntılı inceleyin ↗')+'</p><h2>Bilgi kaynağı</h2><p class="source-list">'+link(s['source'],'Konuyla ilgili sağlık kurumu kaynağı ↗',external=True)+'</p>'
        body=hero(e(s['title']),e(s['intro']),'Danışmanlık alanı')+article_body(content)
        schema={'@type':'Service','name':s['title'],'provider':{'@id':BASE+'/#kurum'},'areaServed':{'@type':'Country','name':'Türkiye'},'url':BASE+'/hizmetler/'+s['slug']+'/','serviceType':'Beslenme danışmanlığı'}
        layout('/hizmetler/'+s['slug']+'/',s['title']+' | Online Diyetisyen Tuğba',s['short']+' Tuğba Şeker Ağaç ile online ve Adana’da beslenme danışmanlığı.',body,extra=[schema])

    blog=hero('Beslenme üzerine<br><span class="accent">iyi sorular, açık yanıtlar.</span>','Online diyetisyen süreci, günlük öğünler ve vücudun işleyişi hakkında kaynaklı bilgi köşesi.','Blog · Beslenme rehberi','tugba-blog-calisma.webp','blog-cover','Diyetisyen Tuğba Şeker Ağaç çalışma masasında beslenme notlarını incelerken')
    filters='<div data-js-only hidden><div class="search-box"><label>Yazılarda ara<input type="search" data-blog-search placeholder="Konu veya kelime yazın…"></label></div><div class="anatomy-controls" aria-label="Yazı kategorisi">'+''.join(f'<button type="button" class="chip" data-filter="{e(c)}" aria-pressed="{str(c=="Tümü").lower()}">{e(c)}</button>' for c in ['Tümü']+sorted({p['category'] for p in POSTS}))+'</div><p class="micro" data-count aria-live="polite">'+str(len(POSTS))+' yazı</p></div>'
    blog+='<section class="section"><div class="wrap">'+filters+post_cards(searchable=True)+'<p class="empty-state" data-empty hidden>Aramanızla eşleşen yazı bulunamadı. Başka bir kelime deneyin veya Tümü kategorisini seçin.</p></div></section>'
    layout('/blog/','Online Diyetisyen Blogu | Beslenme ve Vücudunu Tanı','Online diyetisyen rehberleri, kilo yönetimi, sağlıklı öğünler, insülin direnci ve anatomi üzerine kaynaklı beslenme yazıları.',blog,kind='CollectionPage',cover='tugba-blog-calisma.webp')
    for p in POSTS:
        toc='<nav class="toc" aria-label="Yazı içindekiler"><strong>Bu yazıda</strong>'+''.join(f'<a href="#{e(s["id"])}">{e(s["title"])}</a>' for s in p['sections'])+'</nav>'
        picture=f'<figure>{img(p["image"],p["image_alt"])}<figcaption>{attribution(p["image"])}</figcaption></figure>'
        content=toc+picture+''.join(f'<section id="{e(s["id"])}"><h2>{e(s["title"])}</h2>{s["body"]}</section>' for s in p['sections'])
        content+='<div class="callout">Bu yazı genel bilgilendirme amaçlıdır. Kişisel tanı, tedavi veya beslenme planı yerine geçmez.</div><h2>Kaynaklar ve ilgili bilgiler</h2><ul class="source-list">'+''.join('<li>'+link(u,e(t),external=u.startswith('http'))+'</li>' for t,u in p['sources'])+'</ul><p class="micro">İçerik: '+e(S['name'])+' beslenme bilgi merkezi. Güncelleme ve içerik soruları için '+link('tel:'+S['phone'],e(S['phone_display']))+'.</p>'
        if p.get('editorial_note'):content+='<p class="micro">'+e(p['editorial_note'])+'</p>'
        editorial=p.get('author_type')=='editorial'
        author_name=S['name']+' · Beslenme rehberi' if editorial else S['name']
        author={'@id':BASE+'/#kurum'} if editorial else {'@id':BASE+'/#diyetisyen'}
        top=hero(e(p['title']),e(p['intro']),p['category'])
        top+='<div class="wrap reading-meta"><span>'+link('/kaynaklar/' if editorial else '/kurumsal/',e(author_name))+'</span><time datetime="'+p['date']+'">'+display_date(p['date'])+'</time>'
        if p.get('updated',p['date'])!=p['date']:top+='<span>Güncelleme: <time datetime="'+p['updated']+'">'+display_date(p['updated'])+'</time></span>'
        top+='<span>'+str(reading_time(p))+' dk okuma</span></div>'
        schema={'@type':'BlogPosting','headline':p['title'],'description':p['description'],'image':[BASE+'/assets/images/'+p['image']],'datePublished':p['date'],'dateModified':p.get('updated',p['date']),'author':author,'publisher':{'@id':BASE+'/#kurum'},'mainEntityOfPage':BASE+'/blog/'+p['slug']+'/','inLanguage':'tr-TR'}
        related=[next(x for x in POSTS if x['slug']==slug) for slug in p['related']] if p.get('related') else [x for x in POSTS if x!=p][:3]
        body=top+article_body(content)+'<section class="section soft"><div class="wrap">'+heading('OKUMAYA DEVAM EDİN','İlgili beslenme notları')+post_cards(related)+'</div></section>'
        layout('/blog/'+p['slug']+'/',p.get('seo_title',p['title']+' | Tuğba Şeker Ağaç'),p['description'],body,extra=[schema],cover=p['image'])

    body=hero('Beslenme ve anatomi:<br><span class="accent">vücudunu tanı.</span>','İskelet, kas, yağ dokusu ve sindirim sisteminin beslenmeyle ilişkisini kaynaklı görsellerle keşfedin. Çizimler eğitim içindir; kişisel sağlık durumunuzu göstermez.','Vücudunu Tanı')+'<section class="section"><div class="wrap">'+anatomy()+'</div></section>'
    body+=article_body('<h2>Aynı ağırlık, farklı vücut bileşimi</h2><p>Boy ve kilonun aynı olması kas, yağ ve su miktarlarının da aynı olduğu anlamına gelmez. Genel bir hesaplama aracı dokuları tek tek ölçemez. Değerlendirme yöntemi kişisel ihtiyaca göre belirlenir.</p><h2>Çizimlerdeki temel terimler</h2><ul><li><strong>İskelet:</strong> Skull kafatası, vertebral column omurga, pelvis leğen kemiği, femur uyluk kemiğidir.</li><li><strong>Kas:</strong> Muscle fiber kas lifi, nucleus çekirdek, myofibril miyofibril, sarcomere sarkomerdir.</li><li><strong>Yağ dokusu:</strong> Adipocyte yağ hücresi, nucleus çekirdek, fat droplet yağ damlacığıdır.</li><li><strong>Sindirim:</strong> Stomach mide, small intestine ince bağırsak, large intestine kalın bağırsak, liver karaciğerdir.</li></ul><h2>Görselleri nasıl kullanabilirsiniz?</h2><p>Yukarıdaki konu düğmeleriyle ilgili anatomik çizimi açabilirsiniz. Kaynak bağlantıları ve görsel lisansları her çizimin altında yer alır. Beslenmeyle ilgili kişisel kararlar için yalnızca çizimlere dayanmayın.</p>')
    body+='<section class="section soft"><div class="wrap">'+heading('DAHA FAZLA OKUYUN','Vücudunu tanı yazıları')+post_cards([p for p in POSTS if p['category']=='Vücudunu tanı'])+'</div></section>'
    layout('/vucudunu-tani/','Vücudunu Tanı | Kas, Kemik, Yağ Dokusu ve Beslenme','Kas, iskelet, yağ dokusu ve sindirim anatomisini beslenmeyle birlikte keşfedin. Bilimsel kaynaklı çizimler ve açıklamalar.',body)
    body=hero('BKİ hesaplama.<br><span class="accent">Sonucu anlamıyla birlikte öğren.</span>','20 yaş ve üzerindeki, gebe olmayan yetişkinler için boy ve kilodan beden kütle indeksi hesaplama aracı.','BKİ Hesaplama')+'<section class="section"><div class="wrap split"><div class="prose"><h2>BKİ nasıl hesaplanır?</h2><p>Formül: ağırlık (kg) ÷ boy (m)². Örneğin 170 cm boy ve 65 kg ağırlık için sonuç yaklaşık 22,5 kg/m²’dir.</p><h2>Hesaplama neyi göstermez?</h2><p>BKİ vücut yağ oranını, kas miktarını veya kemik yoğunluğunu ölçmez. Gebelikte ve 20 yaş altında bu yetişkin sınıflandırması kullanılmaz. Sonuç tek başına hastalık tanısı değildir.</p><p>Referans aralıkları: 18,5 altı düşük ağırlık; 18,5–25 arası standart referans; 25–30 arası yüksek ağırlık; 30 ve üzeri obezite sınıflandırması. Sınır değerler hesaplamanın yuvarlanmamış sonucuyla belirlenir.</p></div>'+bmi()+'</div></section>'
    layout('/bki-hesaplama/','BKİ Hesaplama | Beden Kütle İndeksi ve Açıklaması','Boy ve kilonuzla yetişkin beden kütle indeksini hesaplayın. Yağ ölçümü ve tanı yerine geçmeyen BKİ aracının sınırlarını öğrenin.',body)

    body=hero('Video köşesi.<br><span class="accent">Beslenmeyi birlikte konuşalım.</span>','Resmî YouTube kanalından beslenme notları ve tarif videoları. Diğer paylaşımlara sosyal hesaplardan ulaşabilirsiniz.','Videolar & Sosyal hesaplar')+'<section class="section"><div class="wrap">'+video_cards()+'<p class="micro" style="margin-top:25px">Videolar oynat düğmesine basıldığında YouTube üzerinden yüklenir. Video içeriği kişisel beslenme planı yerine geçmez.</p><div class="actions">'+btn(S['youtube'],'YouTube kanalındaki tüm videolar')+'</div></div></section><section class="section soft"><div class="wrap">'+social_block()+'</div></section>'
    layout('/videolar/','Beslenme Videoları & Sosyal Hesaplar | Tuğba Şeker Ağaç','Tuğba Şeker Ağaç YouTube videoları, Instagram paylaşımları, LinkedIn ve Reddit resmî hesap bağlantıları.',body,kind='CollectionPage')

    map_src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3186.411449535723!2d35.32047277594107!3d36.999979472190915!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15288f003a35d1d3%3A0x49795b9186b5af14!2zRGl5ZXRpc3llbiBUdcSfYmEgxZ5la2VyIEHEn2HDpw!5e0!3m2!1str!2str!4v1782773704951!5m2!1str!2str'
    contact=f'''<div class="grid-2"><div class="contact-card">{eyebrow('GÖRÜŞME & İLETİŞİM')}<h3>Online veya ofiste, görüşelim.</h3>{link('tel:'+S['phone'],e(S['phone_display']),'contact-big')}<p>Danışmanlık yöntemi, görüşme kapsamı ve uygun randevu saatleri için iletişim kurabilirsiniz.</p><div class="actions">{btn(WA,'WhatsApp')}{btn('tel:'+S['phone'],'Telefonla ara',True)}</div><p class="micro" style="margin-top:20px">WhatsApp: {e(S['whatsapp_hours'])}<br>Pazar günleri kapalı. Ofis görüşmeleri randevuyla.</p></div><div class="contact-card">{eyebrow('ADANA · SEYHAN')}<h3>Ofis adresi</h3><p>{e(S['address'])}</p><p class="micro">Gelmeden önce randevu saatini ve ofis bilgisini teyit edebilirsiniz.</p>{btn(S['map'],'Haritada konumu aç',True)}<div class="social-list">{link(S['instagram'],'Instagram ↗',external=True)}{link(S['youtube'],'YouTube ↗',external=True)}{link(S['linkedin'],'LinkedIn ↗',external=True)}{link(S['reddit'],'Reddit ↗',external=True)}</div></div></div>'''
    map_html=f'<div class="map-slot"><div><h3>Adana ofis konumu</h3><p class="muted" style="margin-top:16px">Haritayı açtığınızda Google Maps yüklenir.</p><button class="button" type="button" data-map-load data-src="{e(map_src)}">Haritayı bu sayfada göster ↗</button><p style="margin-top:20px">{link(S["map"],"Google Maps’te yol tarifi ↗","text-link",True)}</p></div></div>'
    body=hero('Sorularınız için<br><span class="accent">buradayız.</span>','Türkiye genelinde online beslenme danışmanlığı ve Adana’daki yüz yüze görüşmeler için iletişim kanalları.','İletişim')+'<section class="section"><div class="wrap stack">'+contact+map_html+'</div></section>'+reviews_block()
    layout('/iletisim/','İletişim & Randevu | Diyetisyen Tuğba Şeker Ağaç Adana','0507 036 18 59. Online diyetisyen Tuğba Şeker Ağaç WhatsApp, telefon, Instagram ve Adana Seyhan ofis adresi ile harita bilgileri.',body,kind='ContactPage')
    body=hero('Adana’da<br><span class="accent">yüz yüze beslenme danışmanlığı.</span>','Seyhan’daki ofiste randevulu görüşmeler. Türkiye’nin diğer şehirlerinden online katılım seçeneği.','Adana Diyetisyen','adana-ofis.webp')
    body+=article_body('<h2>Seyhan’daki ofis görüşmeleri</h2><p>Yüz yüze görüşmede sağlık öyküsü, günlük beslenme alışkanlıkları ve beklentiler ele alınır. İlk görüşmeye mevcut tetkiklerinizi, kullandığınız ilaçlara ilişkin bilgileri ve sormak istediğiniz soruları hazırlayarak gelebilirsiniz.</p><h2>Adana’daki günlük yaşamınıza uygun plan</h2><p>İş yerindeki öğle yemekleri, aile sofraları ve dışarıda yemek gibi alışkanlıklar görüşmenin parçasıdır. Yalnızca evde hazırlanabilen bir liste yerine sizin erişebildiğiniz seçenekler değerlendirilir.</p><h2>Ofise ulaşım</h2><p>'+e(S['address'])+'</p><p>Görüşmeler randevuyla yapılır. Haritadaki konumdan yol tarifi alabilir, gelmeden önce telefonla ofis ve randevu bilgisini teyit edebilirsiniz.</p>')
    body+='<section class="section soft"><div class="wrap stack">'+contact+map_html+'</div></section>'
    layout('/adana-diyetisyen/','Adana Diyetisyen Tuğba Şeker Ağaç | Seyhan Ofisi','Adana Seyhan’da diyetisyen Tuğba Şeker Ağaç ile yüz yüze beslenme danışmanlığı. Ofis adresi, telefon, harita ve online görüşme seçeneği.',body)

    sources=hero('Bilginin kaynağı<br><span class="accent">açık olsun.</span>','İçerik yaklaşımı, bilimsel kaynaklar ve kullanılan görsellerin atıf bilgileri.','Kaynaklar & İçerik ilkeleri')
    source_content='<h2>İçerik yaklaşımı</h2><p>Yazılar genel sağlık okuryazarlığını desteklemek için hazırlanır. Kişisel tanı, tedavi veya diyet reçetesi sunmaz. Bilimsel kuruluşlara verilen bağlantılar, bu kuruluşların hizmetlerimizi onayladığı anlamına gelmez.</p><p>İçerik ve kaynaklar düzenli çalışmalarda yeniden değerlendirilebilir. Bir hata fark ederseniz '+link('tel:'+S['phone'],e(S['phone_display']))+' üzerinden bildirebilirsiniz. Son içerik güncelleme: 7 Eylül 2026.</p><h2>Başlıca bilgi kaynakları</h2><ul>'
    for t,u in [('WHO — Sağlıklı beslenme','https://www.who.int/news-room/fact-sheets/detail/healthy-diet'),('CDC — Yetişkin BKİ','https://www.cdc.gov/bmi/adult-calculator/index.html'),('NIDDK — Sindirim sistemi','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works'),('NIH ODS — Kalsiyum','https://ods.od.nih.gov/factsheets/Calcium-Consumer/'),('NHS — Kilo alma','https://www.nhs.uk/live-well/healthy-weight/managing-your-weight/healthy-ways-to-gain-weight/')]:source_content+='<li>'+link(u,e(t),external=True)+'</li>'
    source_content+='</ul><h2>Anatomik görseller</h2><p>OpenStax görselleri Wikimedia Commons’ta belirtilen önceki açık lisanslı sürümlerden alınmıştır. Görseller WebP biçimine dönüştürülmüş ve boyutlandırılmıştır; anatomik etiketler korunmuştur.</p><ul>'+''.join('<li>'+a[1]+': '+attribution(a[5])+'</li>' for a in ANATOMY)+'</ul><h2>Fotoğraf ve diğer görseller</h2><p>Tuğba Şeker Ağaç’ın fotoğrafları, kendisine ait mevcut onlinediyetisyen.online sitesinden alınmıştır. YouTube kapakları ilgili kanal videolarına aittir. Beslenme yazılarındaki yemek görseli yapay zekâyla oluşturulmuş temsili bir sahnedir; ölçülü bir diyet listesi veya danışan sonucu değildir.</p>'
    layout('/kaynaklar/','Kaynaklar ve İçerik İlkeleri | Tuğba Şeker Ağaç','Beslenme içeriklerinde kullanılan bilimsel kaynaklar, anatomi görsellerinin lisansları ve editör iletişim bilgileri.',sources+article_body(source_content))
    privacy=hero('Gizlilik ve<br><span class="accent">veri kullanımı.</span>','Bu sitedeki hesaplamalar ve üçüncü taraf bağlantıları hakkında açıklama.','Gizlilik')
    privacy+=article_body('<h2>BKİ aracına girilen bilgiler</h2><p>Boy, kilo ve yaş bilgileri yalnızca tarayıcınızda hesaplama yapmak için kullanılır. Site bu bilgileri sunucuya göndermez, çerez veya yerel depolamaya kaydetmez. Sayfa yenilendiğinde hesaplama sonucu sıfırlanır.</p><h2>İletişim bağlantıları</h2><p>WhatsApp, Instagram, YouTube, LinkedIn, Reddit ve Google Maps bağlantıları ilgili hizmete yönlendirir. Bu platformların kendi gizlilik ve veri işleme koşulları geçerlidir. WhatsApp bağlantısındaki hazır metin yalnızca görüşme bilgisi istemek içindir; hesaplama bilgileri mesaja eklenmez.</p><h2>Video ve harita</h2><p>YouTube oynatıcısı ve Google haritası ilgili düğmeye bastığınızda yüklenir. Bu işlemde IP adresiniz ve teknik bağlantı bilgileriniz ilgili platformla paylaşılabilir. Video kapakları yerel dosyalardan sunulur.</p><h2>Site altyapısı</h2><p>Bu sürümde analiz, reklam takibi, üyelik veya sağlık bilgisi toplama formu bulunmaz. Barındırma sağlayıcısı hizmetin sunumu ve güvenliği için teknik erişim kayıtları işleyebilir.</p><h2>Sağlık bilgileri ve iletişim</h2><p>Hassas sağlık bilgilerinizi bu web sitesine girmeyin. Danışmanlık sırasında gerekli olabilecek sağlık verilerinin paylaşım ve aydınlatma süreci ayrıca değerlendirilir. Siteye ilişkin sorular için '+link('tel:'+S['phone'],e(S['phone_display']))+' numarasına ulaşabilirsiniz.</p>')
    layout('/gizlilik/','Gizlilik ve Veri Kullanımı | Tuğba Şeker Ağaç','BKİ hesaplayıcısındaki bilgilerin kullanımı, üçüncü taraf video ve harita bağlantıları ile gizlilik açıklamaları.',privacy)
    layout('/404.html','Sayfa bulunamadı | Tuğba Şeker Ağaç','Aradığınız sayfa bulunamadı. Ana sayfaya ve beslenme yazılarına ulaşın.',hero('Bu sayfayı bulamadık.','Adres değişmiş veya yanlış yazılmış olabilir.','404')+'<section class="section"><div class="wrap actions">'+btn('/','Ana sayfaya dön')+btn('/blog/','Blog yazılarını keşfet',True)+'</div></section>',noindex=True)
    xml=Element('urlset',xmlns='http://www.sitemaps.org/schemas/sitemap/0.9')
    for route,_,page_modified in PAGES:
        u=SubElement(xml,'url');SubElement(u,'loc').text=BASE+route;SubElement(u,'lastmod').text=page_modified
    ElementTree(xml).write(OUT/'sitemap.xml',encoding='utf-8',xml_declaration=True)
    (OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'/sitemap.xml\n')
    (OUT/'.nojekyll').write_text('')
    if not PREFIX:(OUT/'CNAME').write_text(BASE.removeprefix('https://')+'\n')
    rss=Element('rss',version='2.0');channel=SubElement(rss,'channel')
    for tag,text in [('title',S['name']+' — Beslenme Blogu'),('link',BASE+'/blog/'),('description','Kaynaklı beslenme yazıları'),('language','tr-tr')]:SubElement(channel,tag).text=text
    for p in POSTS:
        item=SubElement(channel,'item');SubElement(item,'title').text=p['title'];SubElement(item,'link').text=BASE+'/blog/'+p['slug']+'/';SubElement(item,'guid').text=BASE+'/blog/'+p['slug']+'/';SubElement(item,'description').text=p['description']
    ElementTree(rss).write(OUT/'feed.xml',encoding='utf-8',xml_declaration=True)
    print(f'Built {len(PAGES)} indexable pages + 404; {len(POSTS)} posts. Output: {OUT}')

def sync_publish_root():
    """Keep GitHub Pages' configured main/root source ready to serve."""
    manifest=ROOT/'.generated-pages.json'
    previous=json.loads(manifest.read_text()) if manifest.exists() else []
    published=[]
    for source in sorted(OUT.rglob('*')):
        if not source.is_file():continue
        relative=source.relative_to(OUT)
        # Assets are already versioned at the same path. Preserve the owner's CNAME.
        if relative.parts[0]=='assets' or str(relative)=='CNAME':continue
        target=ROOT/relative
        target.parent.mkdir(parents=True,exist_ok=True)
        shutil.copyfile(source,target)
        published.append(relative.as_posix())
    for relative in set(previous)-set(published):
        target=ROOT/relative
        if target.is_file() and target.resolve().is_relative_to(ROOT):target.unlink()
    manifest.write_text(json.dumps(published,ensure_ascii=False,indent=2)+'\n')
    print(f'Synchronized {len(published)} public files to GitHub Pages main/root.')

if __name__=='__main__':
    build()
    if not PREFIX:sync_publish_root()
